name: resto_radar
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter_native_splash: ^2.3.5
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_rating_bar: ^4.0.1
  go_router: ^12.1.0
  google_fonts: ^6.1.0
  http: ^1.1.0
  lottie: ^2.7.0
  readmore: ^2.2.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher.png"
  min_sdk_android: 21


flutter:

  uses-material-design: true
  assets:
    - assets/
